// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_fTmu0w3beLTcgZZaEmxK7QLNMFbjyjo',
    appId: '1:942915309085:web:a7b41db93816c6661500f4',
    messagingSenderId: '942915309085',
    projectId: 'sirene-842ed',
    authDomain: 'sirene-842ed.firebaseapp.com',
    storageBucket: 'sirene-842ed.appspot.com',
    measurementId: 'G-C9MLKJLBWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY52e5CeL58l_GbTFDzv0Ohszszx-pIuE',
    appId: '1:942915309085:android:3f3d406f7e8d15901500f4',
    messagingSenderId: '942915309085',
    projectId: 'sirene-842ed',
    storageBucket: 'sirene-842ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByoFg-WjzD-bQok7R8bUpVtP_sSapT4_8',
    appId: '1:942915309085:ios:615e15726718c4171500f4',
    messagingSenderId: '942915309085',
    projectId: 'sirene-842ed',
    storageBucket: 'sirene-842ed.appspot.com',
    iosClientId: '942915309085-cm5gv4i1nd7dk4b2dknqi4bre8su1h9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByoFg-WjzD-bQok7R8bUpVtP_sSapT4_8',
    appId: '1:942915309085:ios:615e15726718c4171500f4',
    messagingSenderId: '942915309085',
    projectId: 'sirene-842ed',
    storageBucket: 'sirene-842ed.appspot.com',
    iosClientId: '942915309085-cm5gv4i1nd7dk4b2dknqi4bre8su1h9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ninja',
  );
}
